### ISSUE TITLE
Compatibility issues with newest Firedrake install

### ISSUE THREAD

**Issue by Olender** [NDF-Poli-USP/spyro#107]
I am going to try and create a minimal reproducible example for every error that shows up and if it is not related to our software submit an issue in the Firedrake repo.

**Comment by Olender** [comment]
A branch compatible with Firedrake's latest installations is now available. However, it currently supports only triangular and tetrahedral elements. If you need to use the newest version of Firedrake, I recommend switching to this branch. Quadrilateral and hexahedral elements are not yet functional due to a node numbering bug in Firedrake (https://github.com/firedrakeproject/firedrake/issues/3649). Once this issue is patched, I will submit a pull request to merge these changes into the main branch.

**Comment by pbrubeck** [comment]
This issue has been fixed in firedrake. Please let us know everything works as before

**Comment by Olender** [comment]
Thank you for addressing the issue! I have run tests with the latest Firedrake version, and after changing some Functions to Cofunctions, everything is working perfectly now. I appreciate your help.
