### ISSUE TITLE
Improve the notebooks

### ISSUE THREAD

**Issue by Ig-dolci** [NDF-Poli-USP/spyro#95]

**Comment by Olender** [comment]
I have created 6 new jupyter notebooks (currently at https://github.com/Olender/spyro-1/tree/main/notebook_tutorials). This week a PR should be submitted to the main branch.

**Comment by Olender** [comment]
For the moment they are limited to forward propagations and meshing

**Comment by Olender** [comment]
The new notebooks are already on the main branch, but we still need notebooks for gradient solve and inversion
